In [175]:
import numpy as np

grid = np.array([[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,0,9]
       ])

zero_loc = []

In [167]:
def is_possible(x, y, n):
    for i in range(9):
        if grid[x][i] == n:
            return False
        if grid[:,y][i] == n:
            return False
        
    square_x = x // 3 * 3;
    square_y = y // 3 * 3;
    
    for i in range(3):
        for j in range(3):
            if grid[square_x + i][square_y + j] == n:
                return False
    return True

In [168]:
is_possible(6, 7, 1)

True

In [171]:
def populate_zero_loc():
    for i in range(9):
        for j in range(9):
            if grid[i, j] == 0:
                zero_loc.append([i, j])

def solve():
    for x in range(9):
        for y in range(9):
            if grid[x][y] == 0:
                for n in range(1, 10): # numbers 1 through 9
                    if is_possible(x, y, n):
                        grid[x][y] = n
                        solve()
                        grid[x][y] = 0
                return
    print(np.matrix(grid))
    input("More?")

In [130]:
type([])

list

In [135]:
l = ['a']
l.remove('a')

In [136]:
l

[]

In [176]:
solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]


More? 


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


More? 


In [155]:
zero_loc = []